### ISSUE TITLE
Reservas habitaciones

### ISSUE THREAD

**Issue by Nidev-lab** [Amebin/hotel_frontend#24]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Quise reservar una habitación.

## Resultado esperado

• Una vez elegida la habitación poder reservar sin problemas.

## Resultado actual

• Al momento de hacer click en el boton "reservar" se cierra la sesión y no puedo hacer la reserva de la habitacion .

## Captura

![image](https://github.com/Amebin/hotel_frontend/assets/53904695/09ae168b-3113-417e-bfd7-30b3f906909d)
![image](https://github.com/Amebin/hotel_frontend/assets/53904695/1864c52d-a922-4a05-a56b-7253c876b360)
![image](https://github.com/Amebin/hotel_frontend/assets/53904695/ca138010-c789-46a9-b4f0-7957cc94cd5c)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Amebin** [comment]
Buenas noches Nico, corrobore la función de reservas y funciona correctamente, este error podría deberse a que el token se vence 1 hora después de iniciar sesión, ¿necesitas que modifique eso o ponga algún indicador de cuanto tiempo queda para que finalice la sesión?
